---
- hosts: 192.168.56.25
  become: true
  # vars:
  #   ansible_connection: local
  tasks:
    - name: Create a cron job to check server uptime
      cron:
        name: "Check Server Uptime"
        job: "/usr/bin/uptime >> /var/log/server_uptime.log"
        minute: 0
        hour: 0
  
- name: Deploy LAMP Stack App
  hosts: 192.168.56.25
  become: true
  tasks:
    - name: Copy the script to the Slave node
      copy:
        src: C:\Users\Elitebook\Desktop\altschoolS2\Laravel-Project\lampstack.sh
        dest: /tmp/lampstack.sh
        mode: 0755

    - name: Execute the script on the Slave node
      command: /tmp/lampstack.sh